apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-ping
  namespace: demo
spec:
  template:
    spec:
      containers:
        - name: mongo
          image: shaad7/mongo-ping:0.0.1
          args:
            - --ip=172.18.0.2
      restartPolicy: Never
  backoffLimit: 2
